baseURL = 'https://dittocafe.github.io/xihi_edu/'
languageCode = 'zh-cn'
title = 'Xihi留学伴读手记'
theme = 'blowfish'

[params]
  description = '一位美本家长长期主义留学笔记'

[params.homepage]
  layout = "profile"  # 或 "card" "hero"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
    
  [[menu.main]]
    name = '伴读手记'
    url = '/posts/journal/'
    weight = 2
    
  [[menu.main]]
    name = '高中择校'
    url = '/posts/schools/'
    weight = 3
    
  [[menu.main]]
    name = '规划指南'
    url = '/posts/planning/'
    weight = 4
    
  [[menu.main]]
    name = '资源工具箱'
    url = '/toolkit/'
    weight = 5